version: '3.4'

services:
  backend:
    container_name: tel_bot
    env_file: .env
    build:
      context: ./bot
    restart: always
    volumes:
      - ./bot:/app
    networks:
      private_network:
        ipv4_address: 172.25.0.5

  nginx:
    container_name: tel_nginx
    image: nginx:1.17-alpine
    restart: on-failure
    ports:
      - 81:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      private_network:
        ipv4_address: 172.25.0.7
      default:


networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
